### ISSUE TITLE
Ember Server failing after including ember-18next

### ISSUE THREAD

**Issue by mhenley-uk** [OCTRI/ember-i18next#25]
Attempted to pull in the ember addon via "ember install ember-i18next" command which seems to correctly download and install dependencies...seeing new references in both the package.json and bower.json alongside the required files. However on running the "ember server" command the build falls over with the following error...

```javascript
Serving on http://localhost:4200/
ENOENT, no such file or directory 'D:\work\EmberClient\tmp\concat_with_maps-input_base_path-mqBZ53JP.tmp\0\bower_components\i18next\i18next.js'
Error: ENOENT, no such file or directory 'D:\work\EmberClient\tmp\concat_with_maps-input_base_path-mqBZ53JP.tmp\0\bower_components\i18next\i18next.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at ConcatWithMaps.keyForFile (D:\work\EmberClient\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-caching-writer\index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (D:\work\EmberClient\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-caching-writ
    at D:\work\EmberClient\node_modules\ember-cli\node_modules\broccoli-sourcemap-concat\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:6
    at lib$rsvp$$internal$$tryCatch (D:\work\EmberClient\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (D:\work\EmberClient\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (D:\work\EmberClient\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:476:11)
    at lib$rsvp$asap$$flush (D:\work\EmberClient\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

Version info...
Ember : 1.13.11
Ember Data : 1.13.15
jQuery : 1.11.3

**Comment by heathharrelson** [comment]
This happens because the version of i18next isn't specified in the addon's call to `afterInstall`. i18next 2.x only includes a minified version of the .js file. I will have a patch and a bugfix release shortly.

**Comment by heathharrelson** [comment]
Fix is in the related PR, which I will probably release tomorrow. @mhenley-uk - In the meantime, you can get past this issue by updating your bower.json file to require i18next ~1.11.

**Comment by mhenley-uk** [comment]
@heathharrelson Thanks for the quick response, I currently have no requirements for the 2.x release so will continue on with the 1.x for now. Cheers for your work!
