### ISSUE TITLE
unable to use github version of ember-i18next, broccoli build error

### ISSUE THREAD

**Issue by iirving** [OCTRI/ember-i18next#35]
npm version is from this january (https://www.npmjs.com/package/ember-i18next), and is a wrapper of the v1.7 of i18next 

current github version brings it up to v3.3 of i18next.

I've updated my bower.json to  "i18next": "^3.3.1",
and package.json to     "ember-i18next": "git+https://github.com/OCTRI/ember-i18next.git#8185d1d79c62af3fbd7682670821121304cfc2f0",

also made the changes to the environment.js (as pre https://github.com/OCTRI/ember-i18next#configuring-i18next) and  to the ember-cli-build.js
(as pre https://github.com/OCTRI/ember-i18next#including-locale-files)

but on running (after npm install, bower install) ember server, I get a broccoli build error.

ember-cli: 2.6.2
node: 4.4.5
os: darwin x64

what else is needed, to use the most recent ember-i18next?  (also, any change of updating the npm repo?)

**Comment by heathharrelson** [comment]
The master version of ember-i18next is currently work in progress, although it should be working. A new release to NPM will occur soon.

Could you provide the build error and your ember-cli-build.js to help with debugging?

**Comment by iirving** [comment]
hope this helps....

ember-cli-build.js

`/*jshint node:true*/
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var funnel = require('broccoli-funnel');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
  });

  var locales = funnel('app/locales', {
    srcDir: '/',
    destDir:  '/locales'
  });

  return app.toTree();
};
`
build error is : 

The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/ian/Documents/code/lazar/stageten-dashboard/tmp/source_map_concat-input_base_path-14lNNK5U.tmp/0/bower_components/i18next-xhr-backend/i18nextXHRBackend.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/broccoli-caching-writer/index.js:21:10)
    at new ConcatWithMaps (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/broccoli-concat/concat.js:22:17)
    at module.exports (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:348:10)
    at EmberApp.javascript (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1214:12)
    at EmberApp.toArray (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
    at EmberApp.toTree (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
    at module.exports (/Users/ian/Documents/code/lazar/stageten-dashboard/ember-cli-build.js:29:14)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/Users/ian/Documents/code/lazar/stageten-dashboard/node_modules/ember-cli/lib/models/builder.js:54:19)

**Comment by heathharrelson** [comment]
You need to add a dependency for i18next-xhr-backend to bower.json. I have opened #36 to track the documentation updates that need to be made before releasing version 2.0.0.

**Comment by iirving** [comment]
doing a manual installing of i18next-xhr-backend  via bower allowed my to code to build. Many thanks!
